# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26826b4f58b0ea02844ba35f0ecad2087aed46373667e3a22917a77c50cdf146d7bb986cf824ea8658e921fe515fc3d288ba3fd8f57aa08297b28a812bf0d608

test:
  secret_key_base: 996f7a760175f3d9b9debe1152621dc2dfee11c021b20ce0e16facd992a35f70db121c56378127cf8fef886dbf9fa961e7af5a01e31587fda2f096d470caaefa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
